<?php
/**
 * @var $this Scommerce_GoogleTagManagerPro_Block_Checkout_Onepage
 */
?>
<?php
$helper = Mage::helper('scommerce_googletagmanagerpro');
if ($helper->isGA4Enabled()):
    $useGa4 = true;
else:
    $useGa4 = false;
endif;
if ($helper->isUAEnabled()):
    $useUA = true;
else:
    $useUA = false;
endif;
if (!$helper->isEnabled() || !$helper->isEEEnabled()) return; ?>
<?php $cartItems = $this->getCartItems(); 
$userId = Mage::getSingleton('customer/session')->getCustomer()->getId();
?>
<script type='text/javascript'>
//<![CDATA[
/**
 * Called when the user begins the checkout process.
 */
var step_1 =''; var step_2 =''; var step_3 =''; var step_4=''; var step_5='';

gtmPro(document).ready(function($) {
	//console.log("checkout - <?php echo $userId;?>");
	var registered = '<?php echo $this->__('Registered')?>'; var guest = '<?php echo $this->__('Guest')?>';
	var differentAddress = '<?php echo $this->__('Use Different Shipping Address')?>'; var sameAsBilling = '<?php echo $this->__('Use Billing Address For Shipping')?>';
	var shipping = gtmPro.trim(gtmPro('input[name=shipping_method]:checked').closest('li').find('label').contents().get(0).nodeValue);
	var payment = gtmPro.trim(gtmPro('input[name="payment[method]"]:checked').closest('dt').find('label').contents().get(0).nodeValue);
	
	loggedin = "<?php echo $userId;?>";
	if (loggedin.length>0){
		if (step_1!=registered){
			steps(registered, 1);
			step_1=registered;
		}
	}
	else{
		if (step_1!=guest){
			steps(guest, 1);
			step_1=guest;
		}
	}
	if (gtmPro('input[name="shipping[same_as_billing]"]').length){
		//console.log('shipping_different:'+gtmPro('input[name="shipping[different_shipping]"]:checked').val());
		if (gtmPro('input[name="shipping[different_shipping]"]:checked').val()==1){
			if (step_2!=differentAddress){
				steps(differentAddress, 2);
				step_2=differentAddress;
			}
		}
		else{
			if (step_2!=sameAsBilling){
				steps(sameAsBilling, 2);
				step_2=sameAsBilling;
			}
		}
	}
	else if (gtmPro('input[name="billing[use_for_shipping]"]').length){
		if (gtmPro('input[name="billing[use_for_shipping]"]:checked').val()==1){
			if (step_2!=sameAsBilling){
				steps(sameAsBilling, 2);
				step_2=sameAsBilling;
			}
		}
		else{
			if (step_2!=differentAddress){
				steps(differentAddress, 2);
				step_2=differentAddress;
			}
		}
	}
	else{
		//console.log('same_as_billing:'+gtmPro('input[name="shipping[same_as_billing]"]:checked').val());
		if (gtmPro('input[name="shipping[same_as_billing]"]:checked').val()==1){
			if (step_2!=sameAsBilling){
				steps(sameAsBilling, 2);
				step_2=sameAsBilling;
			}
		}
		else{
			if (step_2!=differentAddress){
				steps(differentAddress, 2);
				step_2=differentAddress;
			}
		}
	}
	if (step_3!=shipping){
		steps(shipping, 3);
		step_3=shipping;
	}
	
	if (step_4!=payment){
		steps(payment, 4);
		step_4=payment;
	}
	
	gtmPro('body').on('click change', 'input:radio, input:checkbox, select, button', function(e){
		value=gtmPro(this).attr('value');
		name=gtmPro(this).attr('name');
		//console.log(name+'=='+value);
		sendGoogleData(name,value);
	});	
});

function sendGoogleData(name,value){
	if (name=="billing[register_account]"){
		if (gtmPro('input[name="billing[register_account]"]:checked').val()==1){
			if (step_1!=registered){
				steps(registered, 1);
				step_1=registered;
			}
		}
		else{
			if (step_1!=guest){
				steps(guest, 1);
				step_1=guest;
			}
		}
	}
	else if(name=="shipping[same_as_billing]" || name=="shipping[different_shipping]" || name=="billing[use_for_shipping]"){
		if (name=="shipping[same_as_billing]"){
			if (gtmPro('input[name="shipping[same_as_billing]"]:checked').val()==1){
				if (step_2!=sameAsBilling){
					steps(sameAsBilling, 2);
					step_2=sameAsBilling;
				}
			}
			else{
				if (step_2!=differentAddress){
					steps(differentAddress, 2);
					step_2=differentAddress;
				}
			}
		}
		else if (name=="billing[use_for_shipping]"){
			if (gtmPro('input[name="billing[use_for_shipping]"]:checked').val()==1){
				if (step_2!=sameAsBilling){
					steps(sameAsBilling, 2);
					step_2=sameAsBilling;
				}
			}
			else{
				if (step_2!=differentAddress){
					steps(differentAddress, 2);
					step_2=differentAddress;
				}
			}
		}
		else{
			if (gtmProg('input[name="shipping[different_shipping]"]:checked').val()==1){
				if (step_2!=differentAddress){
					steps(differentAddress, 2);
					step_2=differentAddress;
				}
			}
			else{
				if (step_2!=sameAsBilling){
					steps(sameAsBilling, 2);
					step_2=sameAsBilling;
				}
			}
		}
	}
	else if(name=="shipping_method"){
		if (step_3!=value){
			steps(value, 3);
			step_3=value;
		}
	}
	else if(name=="payment[method]"){
		if (step_4!=value){
			steps(value, 4);
			step_4=value;
		}
	}
}
function steps(value, pos){
	if (value!=undefined){
	//console.log(value,pos);
        <?php if ($useUA): ?>
        if (pos==1){
            <?php $intCtr=0;?>
             dataLayer.push({
                'event': 'checkout',
                'ecommerce': {
                  'checkout': {
                    'actionField': {'step': pos, 'option': value},
                    'products': [
                      <?php foreach($cartItems as $_quoteItem) : ?>
                            <?php $intCtr++;?>
                            <?php if ($_quoteItem->getParentItemId()) continue; ?>
                    {
                      'name': '<?php echo $this->jsQuoteEscape($_quoteItem->getName()) ?>',
                      'id': '<?php echo $this->jsQuoteEscape($_quoteItem->getSku()) ?>',
                      'price': <?php echo $_quoteItem->getBasePrice() ?>,
                      'brand': '<?php echo $this->jsQuoteEscape($helper->getBrand($_quoteItem->getProduct())) ?>',
                      'category': '<?php echo $this->jsQuoteEscape($helper->getQuoteCategoryName($_quoteItem)) ?>',
                      'quantity': '<?php echo $_quoteItem->getQty() ?>'
                      <?php if ($intCtr==count($cartItems)):?>
        }]
                      <?php else:?>
        },
                      <?php endif;?>
                      <?php endforeach; ?>

                 }
               },
               'eventCallback': function() {
                  //document.location = 'checkout.html';
               }
              });
        }
	    else{
            dataLayer.push({
                'event': 'checkoutOption',
                'ecommerce': {
                    'checkout_option': {
                        'actionField': {'step': pos, 'option': value},
                    }
                },
                'eventCallback': function() {
                    //document.location = 'checkout.html';
                }
            });
        }
        <?php endif; ?>
        <?php if ($useGa4): ?>
        if (pos == 1) {
            dataLayer.push({ ecommerce: null });
            dataLayer.push({
                'event': 'begin_checkout',
                'ecommerce': {
                    'items': convertCheckoutItems()
                }
            });
        }
        if (pos == 3) {
            dataLayer.push({ecommerce: null});
            dataLayer.push({
                'event': 'add_shipping_info',
                'ecommerce': {
                    'currency': "<?php echo $helper->getCurrency(); ?>",
                    'shipping_tier': gtmPro.trim(gtmPro('input[name=shipping_method]:checked').closest('li').find('label').contents().get(0).nodeValue),
                    'items': convertPurchaseItems()
                }
            });
        }
        if (pos == 4) {
            dataLayer.push({ecommerce: null});
            dataLayer.push({
                'event': 'add_payment_info',
                'ecommerce': {
                    'currency': "<?php echo $helper->getCurrency(); ?>",
                    'payment_type': gtmPro.trim(gtmPro('input[name="payment[method]"]:checked').closest('dt').find('label').contents().get(0).nodeValue),
                    'items': convertPurchaseItems()
                }
            });
        }
        <?php endif; ?>
    }
}
function convertCheckoutItems() {
    let prods = [];
    <?php foreach ($cartItems as $item): ?>
    <?php
        $itemPrice = $helper->itemIncludedVAT() ? $item->getBasePriceInclTax() : $item->getBasePrice();;
    ?>
    prods.push({
        item_name: '<?php echo $this->jsQuoteEscape($item->getName()) ?>',
        item_id: '<?php echo $this->jsQuoteEscape($item->getSku()) ?>',
        price: formatPrice('<?php echo $itemPrice ?>', false),
        item_brand: '<?php echo $this->jsQuoteEscape($helper->getBrand($item->getProduct())) ?>',
        item_category: '<?php echo $this->jsQuoteEscape($helper->getQuoteCategoryName($item)) ?>',
        quantity: '<?php echo $item->getQty() ?>',
        item_list_name: "<?php echo $item->getTrackingList() ?>",
        item_list_id: getListId("<?php $item->getTrackingList() ?>"),
        affiliation: "<?php echo $helper->getAffiliation(); ?>",
        currency: "<?php echo $helper->getCurrency(); ?>"
    });
    <?php endforeach; ?>

    return prods;
}

function convertPurchaseItems() {
    let prods = [];
    <?php $loop = 1; ?>
    <?php foreach ($cartItems as $item): ?>
    <?php
        $itemPrice = $helper->itemIncludedVAT() ? $item->getBasePriceInclTax() : $item->getBasePrice();;
    ?>
    prods.push({
        item_name: '<?php echo $this->jsQuoteEscape($item->getName()) ?>',
        item_id: '<?php echo $this->jsQuoteEscape($item->getSku()) ?>',
        price: formatPrice('<?php echo $itemPrice ?>', false),
        item_brand: '<?php echo $this->jsQuoteEscape($helper->getBrand($item->getProduct())) ?>',
        item_category: '<?php echo $this->jsQuoteEscape($helper->getQuoteCategoryName($item)) ?>',
        item_list_name: "<?php echo $item['list'] ?>",
        item_list_id: getListId("<?php echo $item['list'] ?>"),
        quantity: '<?php echo $item->getQty() ?>',
        affiliation: "<?php echo $helper->getAffiliation(); ?>",
        currency: "<?php echo $helper->getCurrency(); ?>",
        index: "<?php echo $this->jsQuoteEscape($loop); ?>"
    });
    <?php $loop++; ?>
    <?php endforeach; ?>

    return prods;
}
//]]>

</script>
