<?php
/**
 * @var $this Scommerce_GoogleTagManagerPro_Block_Checkout_Onepage
 */
?>
<?php
$helper = Mage::helper('scommerce_googletagmanagerpro');
if (!$helper->isEnabled() || !$helper->isEEEnabled()) return; ?>
<?php $cartItems = $this->getCartItems(); 
$userId = Mage::getSingleton('customer/session')->getCustomer()->getId();
?>
<script type='text/javascript'>
//<![CDATA[
/**
 * Called when the user begins the checkout process.
 */
var step_1 =''; var step_2 =''; var step_3 =''; var step_4=''; var step_5='';

gtmPro(document).ready(function($) {
	//console.log("checkout - <?php echo $userId;?>");
	var registered = '<?php echo $this->__('Registered')?>'; var guest = '<?php echo $this->__('Guest')?>';
	var differentAddress = '<?php echo $this->__('Use Different Shipping Address')?>'; var sameAsBilling = '<?php echo $this->__('Use Billing Address For Shipping')?>';
	var shipping = gtmPro('input[name=shipping_method]:checked').val();
	var payment = gtmPro('input[name="payment[method]"]:checked').val();
	
	loggedin = "<?php echo $userId;?>";
	if (loggedin.length>0){
		if (step_1!=registered){
			steps(registered, 1);
			step_1=registered;
		}
	}
	else{
		if (step_1!=guest){
			steps(guest, 1);
			step_1=guest;
		}
	}
	if (gtmPro('input[name="shipping[same_as_billing]"]').length){
		//console.log('shipping_different:'+gtmPro('input[name="shipping[different_shipping]"]:checked').val());
		if (gtmPro('input[name="shipping[different_shipping]"]:checked').val()==1){
			if (step_2!=differentAddress){
				steps(differentAddress, 2);
				step_2=differentAddress;
			}
		}
		else{
			if (step_2!=sameAsBilling){
				steps(sameAsBilling, 2);
				step_2=sameAsBilling;
			}
		}
	}
	else if (gtmPro('input[name="billing[use_for_shipping]"]').length){
		if (gtmPro('input[name="billing[use_for_shipping]"]:checked').val()==1){
			if (step_2!=sameAsBilling){
				steps(sameAsBilling, 2);
				step_2=sameAsBilling;
			}
		}
		else{
			if (step_2!=differentAddress){
				steps(differentAddress, 2);
				step_2=differentAddress;
			}
		}
	}
	else{
		//console.log('same_as_billing:'+gtmPro('input[name="shipping[same_as_billing]"]:checked').val());
		if (gtmPro('input[name="shipping[same_as_billing]"]:checked').val()==1){
			if (step_2!=sameAsBilling){
				steps(sameAsBilling, 2);
				step_2=sameAsBilling;
			}
		}
		else{
			if (step_2!=differentAddress){
				steps(differentAddress, 2);
				step_2=differentAddress;
			}
		}
	}
	if (step_3!=shipping){
		steps(shipping, 3);
		step_3=shipping;
	}
	
	if (step_4!=payment){
		steps(payment, 4);
		step_4=payment;
	}
	
	gtmPro('body').on('click change', 'input:radio, input:checkbox, select, button', function(e){
		value=gtmPro(this).attr('value');
		name=gtmPro(this).attr('name');
		//console.log(name+'=='+value);
		sendGoogleData(name,value);
	});	
});

function sendGoogleData(name,value){
	if (name=="billing[register_account]"){
		if (gtmPro('input[name="billing[register_account]"]:checked').val()==1){
			if (step_1!=registered){
				steps(registered, 1);
				step_1=registered;
			}
		}
		else{
			if (step_1!=guest){
				steps(guest, 1);
				step_1=guest;
			}
		}
	}
	else if(name=="shipping[same_as_billing]" || name=="shipping[different_shipping]" || name=="billing[use_for_shipping]"){
		if (name=="shipping[same_as_billing]"){
			if (gtmPro('input[name="shipping[same_as_billing]"]:checked').val()==1){
				if (step_2!=sameAsBilling){
					steps(sameAsBilling, 2);
					step_2=sameAsBilling;
				}
			}
			else{
				if (step_2!=differentAddress){
					steps(differentAddress, 2);
					step_2=differentAddress;
				}
			}
		}
		else if (name=="billing[use_for_shipping]"){
			if (gtmPro('input[name="billing[use_for_shipping]"]:checked').val()==1){
				if (step_2!=sameAsBilling){
					steps(sameAsBilling, 2);
					step_2=sameAsBilling;
				}
			}
			else{
				if (step_2!=differentAddress){
					steps(differentAddress, 2);
					step_2=differentAddress;
				}
			}
		}
		else{
			if (gtmProg('input[name="shipping[different_shipping]"]:checked').val()==1){
				if (step_2!=differentAddress){
					steps(differentAddress, 2);
					step_2=differentAddress;
				}
			}
			else{
				if (step_2!=sameAsBilling){
					steps(sameAsBilling, 2);
					step_2=sameAsBilling;
				}
			}
		}
	}
	else if(name=="shipping_method"){
		if (step_3!=value){
			steps(value, 3);
			step_3=value;
		}
	}
	else if(name=="payment[method]"){
		if (step_4!=value){
			steps(value, 4);
			step_4=value;
		}
	}
}
function steps(value, pos){
	if (value!=undefined){
	//console.log(value,pos);
        if (pos==1){
            <?php $intCtr=0;?>
             dataLayer.push({
                'event': 'checkout',
                'ecommerce': {
                  'checkout': {
                    'actionField': {'step': pos, 'option': value},
                    'products': [
                      <?php foreach($cartItems as $_quoteItem) : ?>
                            <?php $intCtr++;?>
                            <?php if ($_quoteItem->getParentItemId()) continue; ?>
                    {
                      'name': '<?php echo $this->jsQuoteEscape($_quoteItem->getName()) ?>',
                      'id': '<?php echo $this->jsQuoteEscape($_quoteItem->getSku()) ?>',
                      'price': '<?php echo $_quoteItem->getBasePrice() ?>',
                      'brand': '<?php echo $this->jsQuoteEscape($helper->getBrand($_quoteItem->getProduct())) ?>',
                      'category': '<?php echo $this->jsQuoteEscape($helper->getQuoteCategoryName($_quoteItem)) ?>',
                      'quantity': '<?php echo $_quoteItem->getQty() ?>'
                      <?php if ($intCtr==count($cartItems)):?>
        }]
                      <?php else:?>
        },
                      <?php endif;?>
                      <?php endforeach; ?>

                 }
               },
               'eventCallback': function() {
                  //document.location = 'checkout.html';
               }
              });
        }
	    else{
            dataLayer.push({
                'event': 'checkoutOption',
                'ecommerce': {
                    'checkout_option': {
                        'actionField': {'step': pos, 'option': value},
                    }
                },
                'eventCallback': function() {
                    //document.location = 'checkout.html';
                }
            });
        }
    }
}
//]]>

</script>