<?php
/**
 * @var $this Scommerce_GoogleTagManagerPro_Block_Checkout_Success
 */
?>
<?php $helper = Mage::helper('scommerce_googletagmanagerpro');
if (!$helper->isEnabled() || !$helper->isEEEnabled()) return; 
$order = $this->getOrder(); 
if ($helper->sendBaseData()):
	$orderCurrency 		= $order->getBaseCurrencyCode();
	$orderGrandTotal 	= $helper->totalIncludedVAT() ? $order->getBaseGrandTotal() : $order->getBaseGrandTotal() - $order->getBaseTaxAmount();
	$orderShippingTotal	= $order->getBaseShippingAmount();
	$orderTax			= $order->getBaseTaxAmount();
else:
	$orderCurrency 		= $order->getOrderCurrencyCode();
	$orderGrandTotal 	= $helper->totalIncludedVAT() ? $order->getGrandTotal() : $order->getGrandTotal() - $order->getTaxAmount();
	$orderShippingTotal	= $order->getShippingAmount();
	$orderTax			= $order->getTaxAmount();
endif;
$orderItems = $order->getAllVisibleItems();
//exit;
?>
<script type="text/javascript">
//<![CDATA[
	window.dataLayer = window.dataLayer || [];
	<?php $intCtr=0;?>
	dataLayer.push({
          'event': 'purchase',
	  'ecommerce': {
	    'currencyCode': '<?php echo $orderCurrency?>',
		'purchase': {
		  'actionField': {
			'id': '<?php echo $order->getIncrementId()?>',                         // Transaction ID. Required for purchases and refunds.
			'affiliation': '<?php echo $order->getAffiliation() ?>',
			'revenue': '<?php echo $orderGrandTotal?>',                     // Total transaction value (incl. tax and shipping)
			'tax': '<?php echo $orderTax?>',
			'shipping': '<?php echo $orderShippingTotal?>',
			'coupon': '<?php echo $order->getCouponCode() ?>'
		  },
		  'products': [
		  <?php foreach($orderItems as $item): ?>
				<?php $intCtr++;?>
				<?php if($item->getParentItemId()) continue;?>
		  {                            
			'name': '<?php echo $this->jsQuoteEscape($item->getName()) ?>',     // Name or ID is required.
			'id': '<?php echo $this->jsQuoteEscape($item->getSku()) ?>',
			'price': '<?php echo ($helper->sendBaseData()==true ? $item->getBasePrice() : $item->getPrice()) ?>',
			'brand': '<?php echo $this->jsQuoteEscape($helper->getBrand($item->getProduct())) ?>',
			'category': '<?php echo $this->jsQuoteEscape($helper->getQuoteCategoryName($item)) ?>',
			'quantity': <?php echo $item->getQtyOrdered()?>
		  	<?php if ($intCtr==count($orderItems)):?>
}]
			<?php else:?>
},
			<?php endif;?>
			<?php endforeach;?>
		}
	  }
	});
//]]>
</script>